### PR TITLE
add conditional ocl installation

### PR DESCRIPTION
**Pull request by kevinyamauchi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Hello @haesleinhuepf ! The current installation instructions require the user to separately install the correct OCL system based on their OS. This PR adds automatic installation based on OS:

- linux: `ocl-icd-system`
- os x: `ocl_icd_wrapper_apple`

What do you think?

### CODE REVIEW

**Comment by kevinyamauchi** [comment]
@haesleinhuepf , would you prefer I bump the version or build number?

edit: it seems like we should bump the build to keep the version in sync with pypi

**Comment by kevinyamauchi** [comment]
> noarch packages can't have selectors. If the selectors are necessary, please remove noarch: python.

Ah didn't notice this is noarch. Would you be open to moving away from `noarch`?

**Comment by haesleinhuepf** [comment]
> would you prefer I bump the version or build number?

You did it already correctly: the build number :-)

> Ah didn't notice this is noarch. Would you be open to moving away from noarch?

I guess, we can give this a try. Are there any expectable downsides? 

I would wait until Thursday though with such changes. We're running a napari-course and need 100% reliable installation for the students. Afterwards, I'm happy merge this and experiment with things like noarch etc.

**Comment by kevinyamauchi** [comment]
> I guess, we can give this a try. Are there any expectable downsides?

None that I know of. My understanding is that non-noarch recipes will build system-specific versions, but I don't think there will be a difference to the user. Perhaps @jaimergp or @goanpeca can give a better answer.

> I would wait until Thursday though with such changes. We're running a napari-course and need 100% reliable installation for the students. Afterwards, I'm happy merge this and experiment with things like noarch etc.

Makes sense to me!

**Comment by kevinyamauchi** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
The only downside is that we'll have {OS}*{python} builds instead of one, which impose a bigger burden on the CI, but these are quick builds with little footprint so it's ok. However, being a non-noarch, you have to make sure all deps are present across OSs, otherwise the build will fail. With noarch, you only build on Linux, so you can exercise some wishful thinking that _eventually_ the deps will become available. With non-noarch, you need to rebuild the missing builds once the deps are available.

There's another option some feedstocks use: have multiple `noarch` outputs, adding a runtime condition on `__linux` or `__osx` to make it single-platform. This makes it compatible with several Pythons at once too, so it's the best compromise.

**Comment by kevinyamauchi** [comment]
Thanks for the clarification, @jaimergp ! I think for now I will try to get it working using platform/version-specific builds, because as you say, the builds are pretty quick. However, I would be curious how to make the runtime condition `noarch` builds.

@haesleinhuepf , I have a question about the expected installation behavior. When I look at the pypi version of devbio-napari, it looks like python 3.8 and 3.9 are supported. However, the current conda-forge recipe specifies python >= 3.7. I tried installing using the command below and I observed the following where not all packages were installed on all platforms and python versions. These results are consistent with the current CI  build failures in this PR. What is the intended installation behavior? Should only python 3.8 and 3.9 be supported? Is the omission of `cellpose-napari` on windows intentional? 

```bash
mamba create --name devbio-napari-env python=<python version> devbio-napari -c conda-forge
```

| OS      | Python | Environment solves | napari opens | All packages installed? | missing plugins                                                      |
|---------|--------|--------------------|--------------|-------------------------|----------------------------------------------------------------------|
| Windows | 3.7    |  ✅                   | ❌           | ❌                       |  napari-pystackreg, cellpose_napari (no torch), napari-blob-detection                                                                    |
| Windows | 3.8    |  ✅                  | ✅           | ❌                      | cellpose-napari (no torch)                                           |
| Windows | 3.9    |  ✅                  | ✅            | ❌                       | cellpose-napari (no torch)                                           |
| Windows | 3.10   |  ✅                  | ✅            | ❌                       | cellpose-napari (no torch)                                           |
| Mac OS  | 3.7    |  ✅                  | ❌             | ❌                      | napari-pystackreg, cellpose_napari (no torch), napari-blob-detection |
| Mac OS  | 3.8    |  ✅                  | ✅            | ✅                       | -                                                                    |
| Mac OS  | 3.9    |  ✅                  | ✅           | ✅                      | -                                                                    |
| Mac OS  | 3.10   | ❌                   | -            | -                       | -                                                                    |


edit: I looked into it a bit more and it looks like the [`conda-forge` version of pytorch doesn't support Windows](https://anaconda.org/conda-forge/pytorch). Additionally, I don't think we can use the pytorch conda channel since `conda-forge` [doesn't seem to allow channels outside of `conda-forge`](https://github.com/conda-forge/deepforest-feedstock/pull/26#discussion_r786278832). Thus, I don't think `cellpose_napari` is going to install on Windows via conda-forge unless the user installs pytorch on their own ahead of time.

**Comment by haesleinhuepf** [comment]
@jaimergp we can certainly drop support for python 3.7 Any plugins not working on any operating system is unintentional. I tend to remove plugins from the distribution from time to time in case they cause issues of that kind. Btw I install and use napari-cellpose on regular basis on Windows and didn't observe any issues. Maybe pytorch gets installed in some other way we don't see in the CI?

**Comment by kevinyamauchi** [comment]
> Btw I install and use napari-cellpose on regular basis on Windows and didn't observe any issues. Maybe pytorch gets installed in some other way we don't see in the CI?

@haesleinhuepf , I did the installation on a Windows 10 desktop with a fresh Mambaforge installation. I used this command:

```python
mamba create --name devbio-napari-env python=3.9 devbio-napari -c conda-forge
```

and then tried to `import torch` and `import cellpose_napari` from the python console. I received import errors for both and didn't see the `cellpose-napari` plugin in the napari plugin browser/menu. Are you also using the Mambaforge distribution?

edit: if I add the pytorch channel and use conda, pytorch and cellpose will successfully install on Windows. However, if I do the same and install with mamba, pytorch and cellpose do not install.

That is, this works:

```bash
conda create -n napari-dev-bio python=3.9 devbio-napari -c pytorch -c conda-forge
```

and this does not:

```bash
mamba create -n napari-dev-bio python=3.9 devbio-napari -c pytorch -c conda-forge
```
with mamba, the installation completes, but then I get this error:

```python
>>> import torch
Traceback (most recent call last):                                                                                        File "<stdin>", line 1, in <module>                                                                                     File "C:\Users\kevin\mambaforge\envs\napari-dev-bio\lib\site-packages\torch\__init__.py", line 129, in <module>
raise err
OSError: [WinError 182] The operating system cannot run %1. Error loading "C:\Users\kevin\mambaforge\envs\napari-dev-bio\lib\site-packages\torch\lib\shm.dll" or one of its dependencies. 
```

**Comment by haesleinhuepf** [comment]
I've created an issue (link above) to discuss the cellpose issue separately 🌞

**Comment by kevinyamauchi** [comment]
> I've created an issue (link above) to discuss the cellpose issue separately 🌞

Thanks! Sorry, should have done so earlier to avoid polluting this PR.

**Comment by kevinyamauchi** [comment]
As far as I can tell, the path forward is to first decide if we want to keep cellpose-napari as a dependency

- If not, we can continue with the platform/python specific builds and we are good to go.
- If yes, then we need to figure out the best way to include torch as a dependency. 

### pytorch dependency

It looks like having a pytorch dependency is a little complicated because the best way to install `pytorch` is via the `pytorch` channel, but as I understand it, `conda-forge` recipes don't support using non-`conda-forge` channels. Given this, it seems like a system-specific `noarch` (i.e., a conditional based on OS, as suggested by @jaimergp above) would be the best path forward. This may require a two step installation where the user first installs pytorch (`conda install pytorch -c pytorch`) and then installs `devbio-napari`. Best on my experimentation above, it might be possible to install in one step by adding the pytorch channel to the installation command, but I am not sure why it works on `conda` and not `mamba`.

I am curious if @jaimergp or @goanpeca have any tips or examples for depending on pytorch in a `conda-forge` build.

**Comment by jaimergp** [comment]
We do have pytorch on some platforms, so the approach usually is either:

* If the package is noarch, pytorch is a `run` dependency. Users are instructed to supply additional channels in the documentation (e.g. `pytorch::pytorch`).
* Package is non-noarch, you can use selectors (e.g. `# [win]`) to add conditional dependencies. `run_constrained` can be used on Windows to indicate which pytorch versions are compatible _in the event_ the user installs it from somewhere else. The package soft-imports pytorch (e.g. `try / except` clause with a useful error message if pytorch was not found), and code paths control for the possibility of pytorch being absent.

I think `napari` is on 3.8+ only now, so maybe building plugins for Python 3.7 makes little sense. You can add `skip: true  # [py <=37]` to the top-level `build` section. After rerendering, py37 won't be built.

**Comment by jaimergp** [comment]
Note we are adding "extra channel" functionality on the plugin manager so people can add custom origins for their dependencies so we cover for cases like these!

**Comment by kevinyamauchi** [comment]
Thank you, @jaimergp ! These tips are helpful. I think we will try the noarch route.

> Note we are adding "extra channel" functionality on the plugin manager so people can add custom origins for their dependencies so we cover for cases like these!

Awesome!

**Comment by kevinyamauchi** [comment]
@conda-forge-admin, please rerender

**Comment by kevinyamauchi** [comment]
@haesleinhuepf , based on our discussion in https://github.com/haesleinhuepf/devbio-napari/issues/17, I have removed `cellpose-napari`. Hopefully we can get the torch installation sorted and "restore" it soon, as I quite like cellpose.

Based on @jaimergp 's recommendation, I have switched this PR over to using `noarch`, but with multiple outputs based on the target. This will allow us in a follow-up PR add the agreed upon `pytorch` dependency and the user _should_ be able to successfully install `pytorch` by adding the pytorch channel to the installation command.

I added the multiple noarch outputs based on this [knowledgebase article](https://conda-forge.org/docs/maintainer/knowledge_base.html?#noarch-python), but it's my first time doing such a thing, so I'd appreciate any pointers/review from @jaimergp .

What do you all think?

**Comment by jaimergp** [comment]
Excellent @kevinyamauchi!

I think the full solution needs to be documented, so let me give you some pointers:

* We need to add multiple outputs. We could do it with `outputs` or with the conda_build_config.yaml you are using. 
* Let's stick to `conda_build_config.yaml`. This means we need to create build numbers offsets to distinguish the packages. You can follow `pywin32-on-windows` example [here](https://github.com/conda-forge/pywin32-on-windows-feedstock/blob/main/recipe/meta.yaml#L8-L14) (but the multiplier might be *3). You can also use build strings [like this other example](https://github.com/conda-forge/nb_conda-feedstock/tree/main/recipe).
* The target platform needs to be a requirement through virtual packages. For example, linux builds need to depend on `__linux`, macos on `__osx`, windows on `__win`. See [this example too](https://github.com/conda-forge/glances-feedstock/blob/707aacbffbaeccb9152045175168ca2d4e999dbd/recipe/meta.yaml#L30-L36).

Once we get the basic requirements, we can polish the results with a formal review!

**Comment by kevinyamauchi** [comment]
@jaimergp, thank you for the tips! Based on your feedback, I have:

- added the virtual packages
- added output-specific builds via build strings
- renamed `target_os` -> `noarch_platform` for clarity

**Comment by kevinyamauchi** [comment]
Good morning, @haesleinhuepf and @jaimergp . Just a friendly ping for feedback. No worries if you're busy!

**Comment by haesleinhuepf** [comment]
We have another python/napari course this Thursday 😅 Let's merge afterwards and see if it works. 👍

**Comment by jaimergp** [comment]
I think only one build is being generated:

```
validation results:
2022-09-19T14:48:40.2521941Z {
2022-09-19T14:48:40.2522849Z   "noarch/devbio-napari-0.6.0-linux_1.tar.bz2": true
2022-09-19T14:48:40.2523209Z }
```

We might to rerender...?

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
Ok, now we are talking ;) @kevinyamauchi @haesleinhuepf let me know if you like it!

**Comment by haesleinhuepf** [comment]
Hi @jaimergp @kevinyamauchi ,

I'm going to merge this and also push an update to devbio-napari on pypi right after. We can then test if the installation works well in the wild.

Big thanks for your work on this!

**Pull request merged**
